# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce8514a1461761ca0909eeaa8e1e3a5c6d5d84be6cf669b0217b8fbe8e3b0b25c50284c2e5257dba7adb7028e40beef0b2d66acbf9f27205a48b016ccf5f859c

test:
  secret_key_base: 52a3c9307faf7f0690f123c895b7b7b5ac159e1912ca70fba2e9d3614d7648972672f16bf87b5ba74a82de985450f02dd9647266b68ae682d845647e86f2b8fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
